# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(781, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 391, 131))
        self.groupBox.setObjectName("groupBox")
        self.cmb1 = QtWidgets.QComboBox(self.groupBox)
        self.cmb1.setGeometry(QtCore.QRect(10, 40, 221, 22))
        self.cmb1.setObjectName("cmb1")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 161, 16))
        self.label.setObjectName("label")
        self.lb1 = QtWidgets.QLabel(self.groupBox)
        self.lb1.setGeometry(QtCore.QRect(10, 70, 221, 16))
        self.lb1.setObjectName("lb1")
        self.lb2 = QtWidgets.QLabel(self.groupBox)
        self.lb2.setGeometry(QtCore.QRect(10, 90, 221, 16))
        self.lb2.setObjectName("lb2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 160, 391, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 250, 391, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(170, 340, 225, 23))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.btn1 = QtWidgets.QPushButton(self.splitter)
        self.btn1.setObjectName("btn1")
        self.btn2 = QtWidgets.QPushButton(self.splitter)
        self.btn2.setObjectName("btn2")
        self.btn3 = QtWidgets.QPushButton(self.splitter)
        self.btn3.setObjectName("btn3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vectorial"))
        self.groupBox.setTitle(_translate("MainWindow", "Entrada de información"))
        self.label.setText(_translate("MainWindow", "Seleccione shapefile"))
        self.lb1.setText(_translate("MainWindow", "Sistema de referencia"))
        self.lb2.setText(_translate("MainWindow", "Número de atributos"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Geoprocesos"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Salida"))
        self.btn1.setText(_translate("MainWindow", "Ayuda"))
        self.btn2.setText(_translate("MainWindow", "Cancelar"))
        self.btn3.setText(_translate("MainWindow", "Ejecutar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
